# Generated by Django 4.1.7 on 2023-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code_reset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
