# Generated by Django 4.1.7 on 2023-04-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member_code_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='code_reset',
        ),
    ]
