# Generated by Django 4.1.7 on 2023-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoexample_url',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
